---
name: A Life Debugger
tagline: mudah-mudahan bermanfaat untuk umat manusia di muka bumi ini
baseurl: ''
github: https://github.com/fitsyu
twitter: ''
gems:
- jekyll-paginate
markdown: kramdown
disqus:
  shortname: fgio
something: some things
title: my blog
